	.byte "           Deathmaze 5000               "
	.byte " Location is constantly displayed via   "
	.byte "3-D graphics. To move forward one step, "
	.byte "press Z. To turn to the left or right,  "
	.byte "press the left or right arrow. To turn  "
	.byte "around, press X. Only Z actually changes"
	.byte "your position. Additionally, words such "
	.byte "as CHARGE may be helpful in movement.   "
	.byte " At any time, one and two word commands "
	.byte "may be entered. Some useful commands are"
	.byte "OPEN BOX, GET BOX, DROP and HELP. Many  "
	.byte "more exist. To manipulate an object, you"
	.byte "must be on top of it, or be carrying it."
	.byte " To save a game in progress, enter SAVE."
	.byte "This is encouraged. Deathmaze is huge.  "
	.byte "It will take some time to escape.       "
	.byte " The five levels of Deathmaze are con-  "
	.byte "nected by elevators, pits, and science. "
	.byte "Connections are not always obvious.     "
	.byte "             Good Luck!                 "
	.byte "                                        "
	.byte "Copyright 1980 by Med Systems Software  "
	.byte "All rights reserved.                  "
